# Generated by Django 3.2.9 on 2021-11-06 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text='Максимум 150 символів', max_length=150, verbose_name='Текст запитання')),
                ('pub_date', models.DateTimeField(verbose_name='Дата створення')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(help_text='Максимум 100 символів', max_length=100, verbose_name='Текст варіанту')),
                ('votes', models.IntegerField(default=0, verbose_name='Кількість голосів')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
            ],
        ),
    ]
